apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: task-manager
  app.kubernetes.io/component: ai-employee
  app.kubernetes.io/part-of: task-manager-system

namespace: default
