{{- if .Values.persistence.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reporting-agent.fullname" . }}-reports-pvc
  labels:
    {{- include "reporting-agent.labels" . | nindent 4 }}
    component: reports
spec:
  accessModes:
    - {{ .Values.persistence.reports.accessMode }}
  storageClassName: {{ .Values.persistence.reports.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reporting-agent.fullname" . }}-data-pvc
  labels:
    {{- include "reporting-agent.labels" . | nindent 4 }}
    component: data
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
